
import { Forum, Work_Sans } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import ClientLayout from "./clientLayout";
// import LenisProvider from "@/providers/lenisProvider";
// import { Provider } from "react-redux";
// import { PersistGate } from "redux-persist/integration/react";
// import { store, persistor } from "@/store/store";

const forum = Forum({ weight: "400", subsets: ["latin"], display: "swap" });
const workSans = Work_Sans({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Shade & Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${forum.className} ${workSans.className} antialiased`} suppressHydrationWarning>
        {/* <LenisProvider> */}
        <SessionProvider>
          {/* <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}> */}
          <ClientLayout>{children}</ClientLayout>
          {/* </PersistGate>
        </Provider> */}
        </SessionProvider>
        {/* </LenisProvider> */}
      </body>
    </html>
  );
}
