// app/layout.js
import { Forum, Work_Sans } from "next/font/google";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import ClientLayout from "./clientLayout";
import { useEffect } from 'react';
import getLocationFromIP from '@/utils/getLocationFromIP';  // Assuming this is your memoized location function

const forum = Forum({ weight: "400", subsets: ["latin"], display: "swap" });
const workSans = Work_Sans({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Shade & Co.",
  description: "Generated by create next app",
};

export default function RootLayout ({ children }) {
  useEffect(() => {
    const fetchLocation = async () => {
      const ip = await fetch('/api/get-ip')
        .then((res) => res.json())
        .then((data) => data.ip || 'Unknown IP');
      const locationData = await getLocationFromIP(ip);  // Fetch the location
      // Optionally store the location in context or global state if needed
    };

    fetchLocation();
  }, []);

  return (
    <SessionProvider>
      <html lang="en">
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          <link href="./globals.css" rel="stylesheet" />
        </Head>
        <body className={`${forum.className} ${workSans.className} antialiased`} suppressHydrationWarning>
          <ClientLayout>{children}</ClientLayout>
        </body>
      </html>
    </SessionProvider>
  );
}
