"use client";

import { Forum, Work_Sans } from "next/font/google";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import ClientLayout from "./clientLayout";
// import { Provider } from "react-redux";
// import { PersistGate } from "redux-persist/integration/react";
// import { store, persistor } from "@/store/store";

const forum = Forum({ weight: "400", subsets: ["latin"], display: "swap" });
const workSans = Work_Sans({ weight: "400", subsets: ["latin"], display: "swap" });

// export const metadata = {
//   title: "Shade & Co.",
//   description: "Generated by create next app",
// };

export default function RootLayout ({ children }) {

  return (
    <html lang="en">
      <Head>
        {/* <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} /> */}
        <link href="./globals.css" rel="stylesheet" />
      </Head>
      <body className={`${forum.className} ${workSans.className} antialiased`} suppressHydrationWarning>
        <SessionProvider>
          {/* <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}> */}
          <ClientLayout>{children}</ClientLayout>
          {/* </PersistGate>
        </Provider> */}
        </SessionProvider>

      </body>
    </html>
  );
}
