export const footerConfig = {
  logo: {
    src: "/assets/shadeandcorp_log.svg",
    alt: "Shade & Corp",
    width: 80,
    height: 80,
    className: "w-16 md:w-24 h-auto",
  },
  description: "Welcome to Shade & Corp, your ultimate destination for fashion and lifestyle. We bring you the latest trends, premium quality products, and an unparalleled online shopping experience. From chic apparel to essential accessories, we're dedicated to helping you express your unique style. Shop with confidence, enjoy seamless deliveries, and experience customer service that puts you first.",
  navigation: {
    categories: [
      {
        id: "shop",
        name: "Shop",
        sections: [
          {
            id: "categories",
            name: "Categories",
            items: [
              { name: "Men", href: "/category/men" },
              { name: "Women", href: "/category/women" },
              { name: "Kids", href: "/category/kids" },
              { name: "Beauty", href: "/category/beauty" },
              { name: "Home & Living", href: "/category/home" },
            ],
          },
          {
            id: "customer-policies",
            name: "Customer Policies",
            items: [
              { name: "Contact Us", href: "/contact" },
              { name: "FAQ", href: "/faq" },
              { name: "T&C", href: "/terms" },
              { name: "Terms of Use", href: "/terms-of-use" },
              { name: "Track Orders", href: "/orders/track" },
              { name: "Shipping", href: "/shipping" },
              { name: "Cancellation", href: "/cancellation" },
              { name: "Returns", href: "/returns" },
              { name: "Privacy Policy", href: "/privacy" },
            ],
          },
          {
            id: "useful-links",
            name: "Useful Links",
            items: [
              { name: "Blog", href: "/blog" },
              { name: "Careers", href: "/careers" },
              { name: "Site Map", href: "/sitemap" },
              { name: "Corporate Information", href: "/corporate" },
            ],
          },
          {
            id: "featured",
            name: "Featured",
            items: [
              { name: "New Arrivals", href: "/new-arrivals" },
              { name: "Best Sellers", href: "/best-sellers" },
              { name: "Clearance", href: "/clearance" },
              { name: "Gift Cards", href: "/gift-cards" },
              { name: "Store Locator", href: "/store-locator" },
            ],
          },
        ],
      },
    ],
  },
  socials: [
    { name: "Mail", href: "mailto:support@shadeandcorp.com", icon: "gmail-2026/default.svg" },
    { name: "X", href: "https://x.com/shadeandcorp", icon: "x/default.svg" },
    { name: "Instagram", href: "https://www.instagram.com/shadeandcorp/", icon: "instagram/default.svg" },
    { name: "Facebook", href: "https://www.facebook.com/shadeandcorp", icon: "facebook/default.svg" },
    { name: "YouTube", href: "https://www.youtube.com/@shadeandcorp", icon: "youtube/default.svg" },
  ],
  copyright: {
    creator: {
      name: "SutharShantanu",
      href: "https://github.com/SutharShantanu",
    },
    company: {
      name: "Shade & Corp",
      href: "/",
    },
  },
  popularSearches: [
    { name: "Makeup", href: "/search/makeup" },
    { name: "Dresses For Girls", href: "/search/dresses" },
    { name: "T-Shirts", href: "/search/t-shirts" },
    { name: "Sandals", href: "/search/sandals" },
    { name: "Headphones", href: "/search/headphones" },
    { name: "Babydolls", href: "/search/babydolls" },
    { name: "Blazers For Men", href: "/search/blazers" },
    { name: "Handbags", href: "/search/handbags" },
    { name: "Ladies Watches", href: "/search/watches" },
    { name: "Bags", href: "/search/bags" },
    { name: "Sport Shoes", href: "/search/sport-shoes" },
    { name: "Reebok Shoes", href: "/search/reebok" },
    { name: "Puma Shoes", href: "/search/puma" },
    { name: "Boxers", href: "/search/boxers" },
    { name: "Wallets", href: "/search/wallets" },
    { name: "Tops", href: "/search/tops" },
    { name: "Earrings", href: "/search/earrings" },
    { name: "Fastrack Watches", href: "/search/fastrack" },
    { name: "Kurtis", href: "/search/kurtis" },
    { name: "Nike", href: "/search/nike" },
    { name: "Smart Watches", href: "/search/smartwatches" },
    { name: "Titan Watches", href: "/search/titan" },
    { name: "Designer Blouse", href: "/search/designer-blouse" },
    { name: "Gowns", href: "/search/gowns" },
    { name: "Rings", href: "/search/rings" },
    { name: "Cricket Shoes", href: "/search/cricket-shoes" },
    { name: "Forever 21", href: "/search/forever-21" },
    { name: "Eye Makeup", href: "/search/eye-makeup" },
    { name: "Photo Frames", href: "/search/photo-frames" },
    { name: "Punjabi Suits", href: "/search/punjabi-suits" },
    { name: "Bikini", href: "/search/bikini" },
    { name: "Myntra Fashion Show", href: "/search/fashion-show" },
    { name: "Lipstick", href: "/search/lipstick" },
    { name: "Saree", href: "/search/saree" },
    { name: "Watches", href: "/search/watches" },
    { name: "Dresses", href: "/search/dresses" },
    { name: "Lehenga", href: "/search/lehenga" },
    { name: "Nike Shoes", href: "/search/nike-shoes" },
    { name: "Goggles", href: "/search/goggles" },
    { name: "Bras", href: "/search/bras" },
    { name: "Suit", href: "/search/suit" },
    { name: "Chinos", href: "/search/chinos" },
    { name: "Shoes", href: "/search/shoes" },
    { name: "Adidas Shoes", href: "/search/adidas" },
    { name: "Woodland Shoes", href: "/search/woodland" },
    { name: "Jewellery", href: "/search/jewellery" },
    { name: "Designers Sarees", href: "/search/sarees" },
  ],
  address: {
    heading: "Registered Office Address",
    lines: [
      "Buildings Alyssa,",
      "Begonia and Clover situated in Embassy Tech Village,",
      "Outer Ring Road,",
      "Devarabeesanahalli Village,",
      "Varthur Hobli,",
      "Bengaluru – 560103, India",
    ],
    cin: "U72300KA2007PTC041799",
    telephone: "080-40011450"
  }
};
