export const MenTopwear = [
  {
    category: "T-Shirts",
    name: "Classic Cotton T-Shirt",
    brand: "FashionHub",
    image: "https://picsum.photos/200/300",
    original_price: 999,
    discount: 10,
    discounted_price: 899.1,
    country_of_origin: "India",
    date_of_product_launch: "2024-05-15",
    sizes: ["S", "M", "L", "XL"],
    stock: 150,
    description: "A classic cotton t-shirt perfect for everyday wear. Made from high-quality cotton, it offers unmatched comfort and durability. The fabric is soft, breathable, and ideal for all seasons. Available in multiple colors to suit your style, this t-shirt is a must-have in your wardrobe.",
    colors: ["Red", "Blue", "Black"],
  },
  {
    category: "Casual Shirts",
    name: "Linen Casual Shirt",
    brand: "UrbanStyle",
    image: "https://picsum.photos/200/300",
    original_price: 1499,
    discount: 15,
    discounted_price: 1274.15,
    country_of_origin: "India",
    date_of_product_launch: "2024-06-10",
    sizes: ["M", "L", "XL", "XXL"],
    stock: 100,
    description: "A comfortable linen shirt designed for casual outings. Its breathable fabric keeps you cool and relaxed even on warm days. The lightweight material ensures ease of movement, making it perfect for a laid-back yet stylish look. Pair it with jeans or chinos for a complete outfit.",
    colors: ["White", "Beige", "Navy"],
  },
  {
    category: "Formal Shirts",
    name: "Slim Fit Formal Shirt",
    brand: "OfficeWear Co.",
    image: "https://picsum.photos/200/300",
    original_price: 1799,
    discount: 20,
    discounted_price: 1439.2,
    country_of_origin: "India",
    date_of_product_launch: "2024-04-22",
    sizes: ["S", "M", "L", "XL"],
    stock: 75,
    description: "A sleek slim-fit formal shirt tailored for professional settings. The crisp fabric and modern cut give you a sharp and polished appearance. Ideal for office wear or formal events, this shirt is designed to make you stand out. Available in versatile colors to match any suit.",
    colors: ["White", "Light Blue", "Gray"],
  },
  {
    category: "T-Shirts",
    name: "Graphic Print T-Shirt",
    brand: "TrendyTeens",
    image: "https://picsum.photos/200/300",
    original_price: 799,
    discount: 5,
    discounted_price: 759.05,
    country_of_origin: "India",
    date_of_product_launch: "2024-03-18",
    sizes: ["S", "M", "L"],
    stock: 200,
    description: "A trendy graphic print t-shirt designed for the youth. Featuring vibrant and eye-catching designs, this t-shirt is perfect for making a fashion statement. The soft fabric ensures all-day comfort, while the modern fit flatters your physique. A great choice for casual outings or hangouts with friends.",
    colors: ["Yellow", "Green", "Orange"],
  },
  {
    category: "Casual Shirts",
    name: "Denim Shirt",
    brand: "DenimCraft",
    image: "https://picsum.photos/200/300",
    original_price: 1999,
    discount: 25,
    discounted_price: 1499.25,
    country_of_origin: "India",
    date_of_product_launch: "2024-07-01",
    sizes: ["M", "L", "XL"],
    stock: 50,
    description: "A stylish denim shirt that adds a rugged yet fashionable touch to your wardrobe. Made from premium denim, this shirt is durable and versatile. It can be paired with jeans for a double-denim look or with chinos for a more refined style. Perfect for casual outings or weekend adventures.",
    colors: ["Blue", "Black"],
  },
  {
    category: "Formal Shirts",
    name: "Premium Cotton Formal Shirt",
    brand: "LuxuryWear",
    image: "https://picsum.photos/200/300",
    original_price: 2499,
    discount: 30,
    discounted_price: 1749.3,
    country_of_origin: "India",
    date_of_product_launch: "2024-05-30",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 60,
    description: "A premium cotton formal shirt crafted for special occasions. The high-quality fabric ensures a smooth and comfortable fit, while the elegant design exudes sophistication. Whether it's a wedding, business meeting, or formal event, this shirt will make you look sharp and confident.",
    colors: ["White", "Black"],
  },
  {
    category: "T-Shirts",
    name: "Polo Neck T-Shirt",
    brand: "SportyLife",
    image: "https://picsum.photos/200/300",
    original_price: 899,
    discount: 10,
    discounted_price: 809.1,
    country_of_origin: "India",
    date_of_product_launch: "2024-06-05",
    sizes: ["S", "M", "L", "XL"],
    stock: 120,
    description: "A sporty polo neck t-shirt designed for active lifestyles. The breathable fabric keeps you cool during physical activities, while the classic polo neck adds a touch of sophistication. Perfect for sports, casual outings, or even semi-formal occasions. Available in versatile colors to match your style.",
    colors: ["Navy", "Gray", "Maroon"],
  },
  {
    category: "Casual Shirts",
    name: "Checked Casual Shirt",
    brand: "UrbanTrends",
    image: "https://picsum.photos/200/300",
    original_price: 1299,
    discount: 15,
    discounted_price: 1104.15,
    country_of_origin: "India",
    date_of_product_launch: "2024-04-10",
    sizes: ["M", "L", "XL"],
    stock: 80,
    description: "A trendy checked shirt that adds a touch of sophistication to your casual wardrobe. The unique pattern and comfortable fit make it perfect for casual outings or relaxed office environments. Pair it with jeans or trousers for a stylish and effortless look. Available in a variety of colors to suit your preferences.",
    colors: ["Red", "Blue", "Green"],
  },
  {
    category: "Formal Shirts",
    name: "Double Cuff Formal Shirt",
    brand: "EliteWear",
    image: "https://picsum.photos/200/300",
    original_price: 2999,
    discount: 20,
    discounted_price: 2399.2,
    country_of_origin: "India",
    date_of_product_launch: "2024-03-25",
    sizes: ["S", "M", "L", "XL"],
    stock: 40,
    description: "A sophisticated double cuff formal shirt designed for elite occasions. The premium fabric and meticulous tailoring ensure a perfect fit and a polished look. Ideal for weddings, business meetings, or formal events, this shirt will make you stand out with its elegance and style.",
    colors: ["White", "Blue"],
  },
  {
    category: "T-Shirts",
    name: "Oversized T-Shirt",
    brand: "StreetStyle",
    image: "https://picsum.photos/200/300",
    original_price: 699,
    discount: 5,
    discounted_price: 664.05,
    country_of_origin: "India",
    date_of_product_launch: "2024-07-15",
    sizes: ["L", "XL", "XXL"],
    stock: 90,
    description: "An oversized t-shirt that offers a trendy streetwear look. The loose fit and comfortable fabric make it perfect for casual outings or lounging at home. Available in neutral colors, this t-shirt can be paired with jeans, shorts, or joggers for a stylish and relaxed outfit.",
    colors: ["Black", "White", "Gray"],
  },
  {
    category: "Casual Shirts",
    name: "Flannel Shirt",
    brand: "CozyComfort",
    image: "https://picsum.photos/200/300",
    original_price: 1599,
    discount: 10,
    discounted_price: 1439.1,
    country_of_origin: "India",
    date_of_product_launch: "2024-06-20",
    sizes: ["S", "M", "L", "XL"],
    stock: 70,
    description: "A warm and cozy flannel shirt perfect for chilly days. The soft fabric and plaid design make it a timeless addition to your wardrobe. Whether you're heading out for a casual outing or staying indoors, this shirt will keep you comfortable and stylish. Pair it with jeans or trousers for a complete look.",
    colors: ["Red", "Green", "Blue"],
  },
  {
    category: "Formal Shirts",
    name: "Striped Formal Shirt",
    brand: "CorporateStyle",
    image: "https://picsum.photos/200/300",
    original_price: 1899,
    discount: 15,
    discounted_price: 1614.15,
    country_of_origin: "India",
    date_of_product_launch: "2024-05-01",
    sizes: ["S", "M", "L", "XL"],
    stock: 55,
    description: "A professional striped formal shirt designed for office wear. The subtle stripes add a touch of elegance, while the premium fabric ensures comfort throughout the day. Perfect for business meetings or formal events, this shirt will help you make a lasting impression.",
    colors: ["Blue", "Gray"],
  },
  {
    category: "T-Shirts",
    name: "V-Neck T-Shirt",
    brand: "SimpleWear",
    image: "https://picsum.photos/200/300",
    original_price: 599,
    discount: 5,
    discounted_price: 569.05,
    country_of_origin: "India",
    date_of_product_launch: "2024-04-05",
    sizes: ["S", "M", "L"],
    stock: 180,
    description: "A simple and comfortable V-neck t-shirt that is perfect for everyday wear. The soft fabric and relaxed fit make it ideal for casual outings or lounging at home. Available in neutral colors, this t-shirt can be easily paired with jeans, shorts, or joggers for a stylish and effortless look.",
    colors: ["White", "Black", "Gray"],
  },
  {
    category: "Casual Shirts",
    name: "Chambray Shirt",
    brand: "RusticWear",
    image: "https://picsum.photos/200/300",
    original_price: 1399,
    discount: 10,
    discounted_price: 1259.1,
    country_of_origin: "India",
    date_of_product_launch: "2024-07-10",
    sizes: ["M", "L", "XL"],
    stock: 65,
    description: "A lightweight chambray shirt that offers a relaxed and stylish look. The breathable fabric and versatile design make it perfect for casual outings or semi-formal occasions. Pair it with jeans or chinos for a complete outfit. Available in classic colors to suit your style.",
    colors: ["Blue", "White"],
  },
  {
    category: "Formal Shirts",
    name: "French Cuff Formal Shirt",
    brand: "LuxuryLine",
    image: "https://picsum.photos/200/300",
    original_price: 3499,
    discount: 25,
    discounted_price: 2624.25,
    country_of_origin: "India",
    date_of_product_launch: "2024-06-25",
    sizes: ["S", "M", "L", "XL"],
    stock: 30,
    description: "A luxurious French cuff formal shirt designed for elite occasions. The premium fabric and elegant design make it perfect for weddings, business meetings, or formal events. The French cuffs add a touch of sophistication, making this shirt a standout piece in your wardrobe.",
    colors: ["White", "Black"],
  },
];