export const MenTopwear = [
  {
    category: "T-Shirts",
    name: "Classic Cotton T-Shirt",
    brand: "FashionHub",
    image: "https://picsum.photos/200/300",
    original_price: 999,
    discount: 10,
    country_of_origin: "India",
    date_of_product_launch: "2024-05-15",
    sizes: ["S", "M", "L", "XL"],
    stock: 150,
  },
  {
    category: "Casual Shirts",
    name: "Linen Casual Shirt",
    brand: "UrbanStyle",
    image: "https://via.placeholder.com/300x400?text=Linen+Casual+Shirt",
    original_price: 1499,
    discount: 15,
    country_of_origin: "India",
    date_of_product_launch: "2024-06-10",
    sizes: ["M", "L", "XL", "XXL"],
    stock: 100,
  },
  {
    category: "Formal Shirts",
    name: "Slim Fit Formal Shirt",
    brand: "OfficeWear Co.",
    image: "https://picsum.photos/200/300",
    original_price: 1799,
    discount: 5,
    country_of_origin: "Bangladesh",
    date_of_product_launch: "2024-04-20",
    sizes: ["S", "M", "L"],
    stock: 80,
  },
  {
    category: "Sweatshirts",
    name: "Winter Fleece Sweatshirt",
    brand: "CozyWear",
    image: "https://picsum.photos/200/300",
    original_price: 1999,
    discount: 20,
    country_of_origin: "China",
    date_of_product_launch: "2024-07-05",
    sizes: ["M", "L", "XL"],
    stock: 120,
  },
  {
    category: "Sweaters",
    name: "Woolen Crew Neck Sweater",
    brand: "WarmNest",
    image: "https://picsum.photos/200/300",
    original_price: 2499,
    discount: 0,
    country_of_origin: "India",
    date_of_product_launch: "2024-03-18",
    sizes: ["L", "XL", "XXL"],
    stock: 60,
  },
  {
    category: "Jackets",
    name: "Leather Biker Jacket",
    brand: "StreetVogue",
    image: "https://picsum.photos/200/300",
    original_price: 4999,
    discount: 25,
    country_of_origin: "Italy",
    date_of_product_launch: "2024-02-12",
    sizes: ["M", "L"],
    stock: 45,
  },
  {
    category: "Blazers & Coats",
    name: "Tailored Fit Blazer",
    brand: "Elegance Men",
    image: "https://picsum.photos/200/300",
    original_price: 3999,
    discount: 10,
    country_of_origin: "India",
    date_of_product_launch: "2024-01-30",
    sizes: ["S", "M", "L", "XL"],
    stock: 75,
  },
  {
    category: "Suits",
    name: "Three-Piece Suit",
    brand: "Royal Threads",
    image: "https://picsum.photos/200/300",
    original_price: 7999,
    discount: 5,
    country_of_origin: "Turkey",
    date_of_product_launch: "2024-05-01",
    sizes: ["M", "L", "XL"],
    stock: 30,
  },
  {
    category: "Rain Jackets",
    name: "Waterproof Rain Jacket",
    brand: "RainGuard",
    image: "https://picsum.photos/200/300",
    original_price: 2999,
    discount: 15,
    country_of_origin: "Vietnam",
    date_of_product_launch: "2024-06-20",
    sizes: ["S", "M", "L", "XL"],
    stock: 100,
  },
];
