name: Update README with Repo Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg  # Saves output as an SVG file
          token: ${{ secrets.GITHUB_TOKEN }}
          base: repository
          plugin_traffic: yes
          plugin_contributors: yes
          plugin_activity: yes
          plugin_lines: yes

      - name: Update README with Stats
        run: |
          echo "## 📊 Repository Stats" > repo-stats.md
          echo "" >> repo-stats.md
          echo "- **Total Commits:** ![GitHub commit count](https://img.shields.io/github/commit-activity/y/SutharShantanu/shade-and-co)" >> repo-stats.md
          echo "- **Last Commit:** ![GitHub last commit](https://img.shields.io/github/last-commit/SutharShantanu/shade-and-co)" >> repo-stats.md
          echo "- **Contributors:** ![GitHub contributors](https://img.shields.io/github/contributors/SutharShantanu/shade-and-co)" >> repo-stats.md
          echo "- **Issues:** ![GitHub issues](https://img.shields.io/github/issues/SutharShantanu/shade-and-co)" >> repo-stats.md
          echo "- **Pull Requests:** ![GitHub PRs](https://img.shields.io/github/issues-pr/SutharShantanu/shade-and-co)" >> repo-stats.md
          echo "- **Stars:** ![GitHub stars](https://img.shields.io/github/stars/SutharShantanu/shade-and-co?style=social)" >> repo-stats.md
          echo "" >> repo-stats.md
          echo "**Contribution Graph:**" >> repo-stats.md
          echo "![GitHub Contribution Graph](https://github.com/SutharShantanu/shade-and-co/graphs/contributors)" >> repo-stats.md
          cat README.md >> repo-stats.md
          mv repo-stats.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest repo stats" || exit 0
          git push
